### PR TITLE
Update `use:link`'s return type to match svelte's

### PR DESCRIPTION
**Pull request by dtzxporter**
Fixes a compile error with ts.

### CODE REVIEW

**Comment by cdellacqua** [comment]
Thanks again!

Are you using the basic svelte template with typescript support or SvelteKit? I never got those errors with the defaults configured in the basic template, but I may just have an older version with less strict type checking settings

**Comment by cdellacqua** [comment]
Published 2.3.4

**Comment by dtzxporter** [comment]
I'm using latest svelte + the template (webpack instead but that doesn't matter). In order to get proper type checking you need to use `svelte-check`. The Svelte vscode extension also works in a similar manner if you enable the new typescript compiler / type checking settings.

**Comment by cdellacqua** [comment]
Thanks for the advice! I created a new project with the latest template and run svelte-check to fix a couple of other typescript declarations. It should be fine now

**Comment by cdellacqua** [comment]
Published 2.3.6

**Pull request merged**
